import type { Metadata } from "next";
// import { Inter } from "next/font/google";  //font
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { Model } from "./components/models/Model";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arvind Tourism",
  description: "Generated by Arvind",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
      <Navbar/>
      <Model actionLabel="Submit Here" title="Heloo Duniya" isOpen/>
        {children}
      </body>
    </html>
  );
}
